export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Get alerts
export const GET_ALERTS_REQUEST = 'GET_ALERTS_REQUEST';
export const GET_ALERTS_SUCCESS = 'GET_ALERTS_SUCCESS';
export const GET_ALERTS_FAILURE = 'GET_ALERTS_FAILURE';

// Create alert
export const CREATE_ALERT_REQUEST = 'CREATE_ALERT_REQUEST';
export const CREATE_ALERT_SUCCESS = 'CREATE_ALERT_SUCCESS';
export const CREATE_ALERT_FAILURE = 'CREATE_ALERT_FAILURE';

// Update alert
export const UPDATE_ALERT_REQUEST = 'UPDATE_ALERT_REQUEST';
export const UPDATE_ALERT_SUCCESS = 'UPDATE_ALERT_SUCCESS';
export const UPDATE_ALERT_FAILURE = 'UPDATE_ALERT_FAILURE';
export const UPDATE_ALERT_RESET = 'UPDATE_ALERT_RESET';

// Delete alert
export const DELETE_ALERT_REQUEST = 'DELETE_ALERT_REQUEST';
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_FAILURE = 'DELETE_ALERT_FAILURE';

// Get alert
export const GET_ALERT_REQUEST = 'GET_ALERT_REQUEST';
export const GET_ALERT_SUCCESS = 'GET_ALERT_SUCCESS';
export const GET_ALERT_FAILURE = 'GET_ALERT_FAILURE';
export const GET_ALERT_RESET = 'GET_ALERT_RESET';
