// Create
export const CREATE_FAMILY_REQUEST = 'CREATE_FAMILY_REQUEST';
export const CREATE_FAMILY_SUCCESS = 'CREATE_FAMILY_SUCCESS';
export const CREATE_FAMILY_FAILURE = 'CREATE_FAMILY_FAILURE';
export const CREATE_FAMILY_RESET = 'CREATE_FAMILY_RESET';

// Read
export const GET_FAMILY_REQUEST = 'GET_FAMILY_REQUEST';
export const GET_FAMILY_SUCCESS = 'GET_FAMILY_SUCCESS';
export const GET_FAMILY_FAILURE = 'GET_FAMILY_FAILURE';
export const GET_FAMILY_RESET = 'GET_FAMILY_RESET';

// Update
export const UPDATE_FAMILY_REQUEST = 'UPDATE_FAMILY_REQUEST';
export const UPDATE_FAMILY_SUCCESS = 'UPDATE_FAMILY_SUCCESS';
export const UPDATE_FAMILY_FAILURE = 'UPDATE_FAMILY_FAILURE';
export const UPDATE_FAMILY_RESET = 'UPDATE_FAMILY_RESET';

// Delete
export const DELETE_FAMILY_REQUEST = 'DELETE_FAMILY_REQUEST';
export const DELETE_FAMILY_SUCCESS = 'DELETE_FAMILY_SUCCESS';
export const DELETE_FAMILY_FAILURE = 'DELETE_FAMILY_FAILURE';
export const DELETE_FAMILY_RESET = 'DELETE_FAMILY_RESET';

// List
export const GET_FAMILIES_REQUEST = 'GET_FAMILIES_REQUEST';
export const GET_FAMILIES_SUCCESS = 'GET_FAMILIES_SUCCESS';
export const GET_FAMILIES_FAILURE = 'GET_FAMILIES_FAILURE';
export const GET_FAMILIES_RESET = 'GET_FAMILIES_RESET';
