// plural
export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST';
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS';
export const GET_FEATURES_FAIL = 'GET_FEATURES_FAIL';
export const GET_FEATURES_RESET = 'GET_FEATURES_RESET';

// singular
export const GET_FEATURE_REQUEST = 'GET_FEATURE_REQUEST';
export const GET_FEATURE_SUCCESS = 'GET_FEATURE_SUCCESS';
export const GET_FEATURE_FAIL = 'GET_FEATURE_FAIL';
export const GET_FEATURE_RESET = 'GET_FEATURE_RESET';

// update
export const UPDATE_FEATURE_REQUEST = 'UPDATE_FEATURE_REQUEST';
export const UPDATE_FEATURE_SUCCESS = 'UPDATE_FEATURE_SUCCESS';
export const UPDATE_FEATURE_FAIL = 'UPDATE_FEATURE_FAIL';
export const UPDATE_FEATURE_RESET = 'UPDATE_FEATURE_RESET';

