
// singular
export const SELECT_MINISTRY_REQUEST = "SELECT_MINISTRY_REQUEST";
export const SELECT_MINISTRY_SUCCESS = "SELECT_MINISTRY_SUCCESS";
export const SELECT_MINISTRY_FAIL = "SELECT_MINISTRY_FAIL";
export const SELECT_MINISTRY_RESET = "SELECT_MINISTRY_RESET";