// update
export const MINISTRY_UPDATE_REQUEST = "MINISTRY_UPDATE_REQUEST";
export const MINISTRY_UPDATE_SUCCESS = "MINISTRY_UPDATE_SUCCESS";
export const MINISTRY_UPDATE_FAIL = "MINISTRY_UPDATE_FAIL";
export const MINISTRY_UPDATE_RESET = "MINISTRY_UPDATE_RESET";

// singular
export const SELECT_MINISTRY_REQUEST = "SELECT_MINISTRY_REQUEST";
export const SELECT_MINISTRY_SUCCESS = "SELECT_MINISTRY_SUCCESS";
export const SELECT_MINISTRY_FAIL = "SELECT_MINISTRY_FAIL";
export const SELECT_MINISTRY_RESET = "SELECT_MINISTRY_RESET";

// main ministry
export const MAIN_MINISTRY_REQUEST = "MAIN_MINISTRY_REQUEST";
export const MAIN_MINISTRY_SUCCESS = "MAIN_MINISTRY_SUCCESS";
export const MAIN_MINISTRY_FAIL = "MAIN_MINISTRY_FAIL";
export const MAIN_MINISTRY_RESET = "MAIN_MINISTRY_RESET";