export const PARTNER_LIST_REQUEST = "PARTNER_LIST_REQUEST";
export const PARTNER_LIST_SUCCESS = "PARTNER_LIST_SUCCESS";
export const PARTNER_LIST_FAIL = "PARTNER_LIST_FAIL";
export const PARTNER_LIST_RESET = "PARTNER_LIST_RESET";

export const PARTNER_LIST_ONE_REQUEST = "PARTNER_LIST_ONE_REQUEST";
export const PARTNER_LIST_ONE_SUCCESS = "PARTNER_LIST_ONE_SUCCESS";
export const PARTNER_LIST_ONE_FAIL = "PARTNER_LIST_ONE_FAIL";
export const PARTNER_LIST_ONE_RESET = "PARTNER_LIST_ONE_RESET";

export const PARTNER_CREATE_REQUEST = "PARTNER_CREATE_REQUEST";
export const PARTNER_CREATE_SUCCESS = "PARTNER_CREATE_SUCCESS";
export const PARTNER_CREATE_FAIL = "PARTNER_CREATE_FAIL";

export const PARTNER_UPDATE_REQUEST = "PARTNER_UPDATE_REQUEST";
export const PARTNER_UPDATE_SUCCESS = "PARTNER_UPDATE_SUCCESS";
export const PARTNER_UPDATE_FAIL = "PARTNER_UPDATE_FAIL";
export const PARTNER_UPDATE_RESET = "PARTNER_UPDATE_RESET";

export const PARTNER_DELETE_REQUEST = "PARTNER_DELETE_REQUEST";
export const PARTNER_DELETE_SUCCESS = "PARTNER_DELETE_SUCCESS";
export const PARTNER_DELETE_FAIL = "PARTNER_DELETE_FAIL";

export const PARTNER_SELECT = "PARTNER_SELECT";

export const GET_PARTNER_LOGO = "GET_PARTNER_LOGO";
export const UPDATE_PARTNER_LOGO = "UPDATE_PARTNER_LOGO";