export const GET_PAYMENTINFO_REQUEST = 'GET_PAYMENTINFO_REQUEST';
export const GET_PAYMENTINFO = 'GET_PAYMENTINFO';

export const GET_PAYMENT_DETAILS_REQUEST = 'GET_PAYMENT_DETAILS_REQUEST';
export const GET_PAYMENT_DETAILS_SUCESSES = 'GET_PAYMENT_DETAILS_SUCESSES';
export const GET_PAYMENT_DETAILS_FAIL = 'GET_PAYMENT_DETAILS_FAIL';
export const GET_PAYMENT_DETAILS_RESET = 'GET_PAYMENT_DETAILS_RESET';

export const GET_RECEIPT_REQUEST = 'GET_RECEIPT_REQUEST';
export const GET_RECEIPT_SUCESSES = 'GET_RECEIPT_SUCESSES';
export const GET_RECEIPT_FAIL = 'GET_RECEIPT_FAIL';
export const GET_RECEIPT_RESET = 'GET_RECEIPT_RESET';

export const GET_RECEIPTS_REQUEST = 'GET_RECEIPTS_REQUEST';
export const GET_RECEIPTS_SUCESSES = 'GET_RECEIPTS_SUCESSES';
export const GET_RECEIPTS_FAIL = 'GET_RECEIPTS_FAIL';
export const GET_RECEIPTS_RESET = 'GET_RECEIPTS_RESET';

export const DELETE_RECEIPT_REQUEST = 'DELETE_RECEIPT_REQUEST';
export const DELETE_RECEIPT_SUCESSES = 'DELETE_RECEIPT_SUCESSES';
export const DELETE_RECEIPT_FAIL = 'DELETE_RECEIPT_FAIL';
export const DELETE_RECEIPT_RESET = 'DELETE_RECEIPT_RESET';

export const UPDATE_RECEIPT_REQUEST = 'UPDATE_RECEIPT_REQUEST';
export const UPDATE_RECEIPT_SUCESSES = 'UPDATE_RECEIPT_SUCESSES';
export const UPDATE_RECEIPT_FAIL = 'UPDATE_RECEIPT_FAIL';
export const UPDATE_RECEIPT_RESET = 'UPDATE_RECEIPT_RESET';
