export const GET_SUBSCRIPTIONS_REQUEST = 'GET_SUBSCRIPTIONS_REQUEST'
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS'
export const CART_SUBSCRIPTION = 'CART_SUBSCRIPTION'
export const SUBSCRIPTION_TO_UPGRADE_TO = 'SUBSCRIPTION_TO_UPGRADE_TO'
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION'
export const GET_SUBSCRIPTION_REQUEST = 'GET_SUBSCRIPTION_REQUEST'

export const UPDATED_SUBSCRIPTION_REQUEST = 'UPDATED_SUBSCRIPTION_REQUEST'
export const UPDATED_SUBSCRIPTION_SUCESS = 'UPDATED_SUBSCRIPTION_SUCESS'
export const UPDATED_SUBSCRIPTION_FAIL = 'UPDATED_SUBSCRIPTION_FAIL'
export const UPDATED_SUBSCRIPTION_RESET = 'UPDATED_SUBSCRIPTION_RESET'

export const UPDATE_FREE_SUBSCRIPTION_REQUEST =
  'UPDATE_FREE_SUBSCRIPTION_REQUEST'
export const UPDATE_FREE_SUBSCRIPTION_SUCESS = 'UPDATE_FREE_SUBSCRIPTION_SUCESS'
export const UPDATE_FREE_SUBSCRIPTION_FAIL = 'UPDATE_FREE_SUBSCRIPTION_FAIL'
export const UPDATE_FREE_SUBSCRIPTION_RESET = 'UPDATE_FREE_SUBSCRIPTION_RESET'

// admin constants
export const SUBSCRIPTIONS_LIST_REQUEST = 'SUBSCRIPTIONS_LIST_REQUEST'
export const SUBSCRIPTIONS_LIST_SUCCESS = 'SUBSCRIPTIONS_LIST_SUCCESS'
export const SUBSCRIPTIONS_LIST_FAIL = 'SUBSCRIPTIONS_LIST_FAIL'

export const SUBSCRIPTION_DETAILS_REQUEST = 'SUBSCRIPTION_DETAILS_REQUEST'
export const SUBSCRIPTION_DETAILS_SUCCESS = 'SUBSCRIPTION_DETAILS_SUCCESS'
export const SUBSCRIPTION_DETAILS_FAIL = 'SUBSCRIPTION_DETAILS_FAIL'

export const SUBSCRIPTION_DELETE_REQUEST = 'SUBSCRIPTION_DELETE_REQUEST'
export const SUBSCRIPTION_DELETE_SUCCESS = 'SUBSCRIPTION_DELETE_SUCCESS'
export const SUBSCRIPTION_DELETE_FAIL = 'SUBSCRIPTION_DELETE_FAIL'

export const SUBSCRIPTION_CREATE_REQUEST = 'SUBSCRIPTION_CREATE_REQUEST'
export const SUBSCRIPTION_CREATE_SUCCESS = 'SUBSCRIPTION_CREATE_SUCCESS'
export const SUBSCRIPTION_CREATE_FAIL = 'SUBSCRIPTION_CREATE_FAIL'
export const SUBSCRIPTION_CREATE_RESET = 'SUBSCRIPTION_CREATE_RESET'

export const SUBSCRIPTION_UPDATE_REQUEST = 'SUBSCRIPTION_UPDATE_REQUEST'
export const SUBSCRIPTION_UPDATE_SUCCESS = 'SUBSCRIPTION_UPDATE_SUCCESS'
export const SUBSCRIPTION_UPDATE_FAIL = 'SUBSCRIPTION_UPDATE_FAIL'
export const SUBSCRIPTION_UPDATE_RESET = 'SUBSCRIPTION_UPDATE_RESET'
