export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USERS_RESET = 'GET_USERS_RESET';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const GET_USER_RESET = 'GET_USER_RESET';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_DELETE_NMI_SUBSCRIPTION_REQUEST =
  'USER_DELETE_NMI_SUBSCRIPTION_REQUEST';
export const USER_DELETE_NMI_SUBSCRIPTION_SUCCESS =
  'USER_DELETE_NMI_SUBSCRIPTION_SUCCESS';
export const USER_DELETE_NMI_SUBSCRIPTION_FAIL =
  'USER_DELETE_NMI_SUBSCRIPTION_FAIL';

export const SERVER_VIDEO_UPLOAD_REQUEST = 'SERVER_VIDEO_UPLOAD_REQUEST';
export const SERVER_VIDEO_UPLOAD_SUCCESS = 'SERVER_VIDEO_UPLOAD_SUCCESS';
export const SERVER_VIDEO_UPLOAD_FAIL = 'SERVER_VIDEO_UPLOAD_FAIL';
export const SERVER_VIDEO_UPLOAD_RESET = 'SERVER_VIDEO_UPLOAD_RESET';
