// Get Videos
export const GET_VIDEOS_REQUEST = 'GET_VIDEOS_REQUEST';
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';
export const GET_VIDEOS_RESET = 'GET_VIDEOS_RESET';

// get video
export const GET_VIDEO_REQUEST = 'GET_VIDEO_REQUEST';
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';
export const GET_VIDEO_FAILURE = 'GET_VIDEO_FAILURE';
export const GET_VIDEO_RESET = 'GET_VIDEO_RESET';

// delete video
export const VIDEO_DELETE_REQUEST = 'VIDEO_DELETE_REQUEST';
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS';
export const VIDEO_DELETE_FAILURE = 'VIDEO_DELETE_FAILURE';

// update video
export const VIDEO_UPDATE_REQUEST = 'VIDEO_UPDATE_REQUEST';
export const VIDEO_UPDATE_SUCCESS = 'VIDEO_UPDATE_SUCCESS';
export const VIDEO_UPDATE_FAILURE = 'VIDEO_UPDATE_FAILURE';
export const VIDEO_UPDATE_RESET = 'VIDEO_UPDATE_RESET';
// comments
export const GET_VIDEO_COMMENTS_REQUEST = 'GET_VIDEO_COMMENTS';
export const GET_VIDEO_COMMENTS_SUCCESS = 'GET_VIDEO_COMMENTS_SUCCESS';
export const GET_VIDEO_COMMENTS_FAILURE = 'GET_VIDEO_COMMENTS_FAILURE';
export const GET_VIDEO_COMMENTS_RESET = 'GET_VIDEO_COMMENTS_RESET';

// add comment
export const ADD_VIDEO_COMMENT_REQUEST = 'ADD_VIDEO_COMMENT_REQUEST';
export const ADD_VIDEO_COMMENT_SUCCESS = 'ADD_VIDEO_COMMENT_SUCCESS';
export const ADD_VIDEO_COMMENT_FAILURE = 'ADD_VIDEO_COMMENT_FAILURE';

// Get Videos from WOWZA Server!!
export const GET_SERVER_VIDEOS_REQUEST = 'GET_SERVER_VIDEOS_REQUEST';
export const GET_SERVER_VIDEOS_SUCCESS = 'GET_SERVER_VIDEOS_SUCCESS';
export const GET_SERVER_VIDEOS_FAILURE = 'GET_SERVER_VIDEOS_FAILURE';
export const GET_SERVER_VIDEOS_RESET = 'GET_SERVER_VIDEOS_RESET';
